displayName=Healing sounds
author=darkxaotik
description=Makes a sound when you get healed from Sanguinesti staff or Blood Fury
tags=sound, sounds, heal, pvm
version=1.0.0
plugins=com.HealingSounds.HealingSoundsPlugin
build=standard